<?php
/**
 * @file
 * Contains zh.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function zh_theme()
{
   return [
     'front' => [
       'variables' => ['vars' => NULL],
       'template' => 'front',
     ],
     'about_us' => [
       'variables' => ['vars' => NULL],
       'template' => 'about-us',
     ],
     'projects' => [
       'variables' => ['vars' => NULL],
       'template' => 'projects',
     ],
     'affiliates' => [
       'variables' => ['vars' => NULL],
       'template' => 'affiliates',
     ],
     'company_culture' => [
       'variables' => ['vars' => NULL],
       'template' => 'company-culture',
     ],
     'join_us' => [
       'variables' => ['vars' => NULL],
       'template' => 'join-us',
     ],
     'contact_us' => [
       'variables' => ['vars' => NULL],
       'template' => 'contact-us',
     ],
   ];
}

/**
 * Implements hook_form_alter().
 */
function zh_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  switch ($form_id) {
    case 'user_login_form':
      $form['#submit'][] = '_redirect_to_admin_content_page';
      break;
  }
}

/**
 * Additional form submit callback to set the redirect url.
 */
function _redirect_to_admin_content_page($form, FormStateInterface $form_state)
{
  $form_state->setRedirect('system.admin_content');
}


 /**
  * Implements hook_mail().
  */
  /*
function ficelles_mail($key, &$message, $params)
{
  switch ($key) {
    case 'ficelles_mail':
      $message['subject'] = $params['subject'];
      $message['body']    = array_map(function ($p) {
        return Markup::create($p);
      }, $params['infos']);
      break;
  }
}
*/
