<?php
/**
 * @file
 * Contains zh.module.
 */

/**
 * Implements hook_theme().
 */
function zh_theme()
{
   return [
     'front' => [
       'variables' => ['vars' => NULL],
       'template' => 'front',
     ],
     'about_us' => [
       'variables' => ['vars' => NULL],
       'template' => 'about-us',
     ],
     'projects' => [
       'variables' => ['vars' => NULL],
       'template' => 'projects',
     ],
     'affiliates' => [
       'variables' => ['vars' => NULL],
       'template' => 'affiliates',
     ],
     'company_culture' => [
       'variables' => ['vars' => NULL],
       'template' => 'company-culture',
     ],
     'join_us' => [
       'variables' => ['vars' => NULL],
       'template' => 'join-us',
     ],
     'contact_us' => [
       'variables' => ['vars' => NULL],
       'template' => 'contact-us',
     ],
   ];
}


 /**
  * Implements hook_mail().
  */
  /*
function ficelles_mail($key, &$message, $params)
{
  switch ($key) {
    case 'ficelles_mail':
      $message['subject'] = $params['subject'];
      $message['body']    = array_map(function ($p) {
        return Markup::create($p);
      }, $params['infos']);
      break;
  }
}
*/
